# -------------------
# CONFIG
# -------------------
DEVICE_IP = "127.0.0.1"      # Change to your adb device's IP address
DEVICE_PORT = 16384          # Change to your adb device's port number
TEMPLATE_DIR = "templates"
MATCH_THRESHOLD = 0.8
SESSION_RESET_INTERVAL = (5400, 10800)  # 1.5-3 hours

# -------------------
# DETECTION TEMPLATES
# -------------------
STAGE_MAINMENU_TEMPLATE = ["MAINMENU_1.png"]
STAGE_PURCHASE_ITEM_TEMPLATE = ["PURCHASE_ITEM_1.png"]
STAGE_GAME_START_TEMPLATE = ["GAME_START_1.png"]
STAGE_GAME_RELAY_TEMPLATE = ["GAME_RELAY_1.png"]
STAGE_GAME_COMPLETE_TEMPLATE = ["GAME_COMPLETE_1.png"]
STAGE_MYSTERY_BOX_TEMPLATE = ["MYSTERY_BOX_1.png"]
STAGE_CONGRATULATIONS_TEMPLATE = ["CONGRATULATIONS_1.png", "CONGRATULATIONS_2.png"]
STAGE_LEVEL_UP_TEMPLATE = ["LEVEL_UP_1.png"]
STAGE_RELIC_COMPLETE_TEMPLATE = ["RELIC_COMPLETE_1.png"]
STAGE_RELIC_CLAIM_TEMPLATE = ["RELIC_CLAIM_1.png"]
STAGE_DAILY_CHECKIN_TEMPLATE = ["DAILY_CHECKIN_1.png"]
STAGE_DAILY_TREASURE_TEMPLATE = ["DAILY_TREASURE_1.png"]
STAGE_ENTER_LEAGUE_TEMPLATE = ["ENTER_LEAGUE_1.png"]
STAGE_LEAGUE_RESULTS_TEMPLATE = ["LEAGUE_RESULTS_1.png"]
STAGE_ANTI_BOT_TEMPLATE = ["ANTI_BOT_1.png"]
STAGE_CONNECTION_LOST_TEMPLATE = ["CONNECTION_LOST_1.png"]
STAGE_PREVIOUS_RANK_RESULTS_TEMPLATE = ["PREVIOUS_RANK_RESULTS_1.png"]

# -------------------
# BOOST TEMPLATES
# -------------------
BOOST_DOUBLE_COINS_TEMPLATE = ["BOOST_DOUBLE_COINS_1.png"]
BOOST_15P_SCORE_BONUS_TEMPLATE = ["BOOST_15P_SCORE_BONUS_1.png"]
BOOST_M15P_HP_DRAIN_TEMPLATE = ["BOOST_M15P_HP_DRAIN_1.png"]
BOOST_REVIVE_ONCE_WITH_80HP_TEMPLATE = ["BOOST_REVIVE_ONCE_WITH_80HP_1.png"]
BOOST_70P_CRUSH_CHANCE_TEMPLATE = ["BOOST_70P_CRUSH_CHANCE_1.png"]
BOOST_17P_BASE_SPEED_TEMPLATE = ["BOOST_17P_BASE_SPEED_1.png"]
BOOST_GOLD_COIN_MAGIC_TEMPLATE = ["BOOST_GOLD_COIN_MAGIC_1.png"]
BOOST_M30P_COLLISION_DAMAGE_TEMPLATE = ["BOOST_M30P_COLLISION_DAMAGE_1.png"]
BOOST_20P_HP_FROM_POTIONS_TEMPLATE = ["BOOST_20P_HP_FROM_POTIONS_1.png"]
BOOST_MAGNETIC_AURA_TEMPLATE = ["BOOST_MAGNETIC_AURA_1.png"]
BOOST_2PIT_LIFTS_TEMPLATE = ["BOOST_2PIT_LIFTS_1.png"]

# -------------------
# STAGE MAP
# -------------------
STAGE_TEMPLATES = {
    # higher priority stages first
    "ANTI_BOT":        STAGE_ANTI_BOT_TEMPLATE,
    "CONNECTION_LOST": STAGE_CONNECTION_LOST_TEMPLATE,
    "DAILY_CHECKIN":   STAGE_DAILY_CHECKIN_TEMPLATE,
    "DAILY_TREASURE":  STAGE_DAILY_TREASURE_TEMPLATE,
    "LEVEL_UP":        STAGE_LEVEL_UP_TEMPLATE,
    "CONGRATULATIONS": STAGE_CONGRATULATIONS_TEMPLATE,
    "RELIC_COMPLETE":  STAGE_RELIC_COMPLETE_TEMPLATE,
    "RELIC_CLAIM":     STAGE_RELIC_CLAIM_TEMPLATE,
    "ENTER_LEAGUE":    STAGE_ENTER_LEAGUE_TEMPLATE,
    "LEAGUE_RESULTS":  STAGE_LEAGUE_RESULTS_TEMPLATE,
    "PREVIOUS_RANK_RESULTS": STAGE_PREVIOUS_RANK_RESULTS_TEMPLATE,
    "MAINMENU":        STAGE_MAINMENU_TEMPLATE,
    "PURCHASE_ITEM":   STAGE_PURCHASE_ITEM_TEMPLATE,
    "GAME_START":      STAGE_GAME_START_TEMPLATE,
    "GAME_RELAY":      STAGE_GAME_RELAY_TEMPLATE,
    "GAME_COMPLETE":   STAGE_GAME_COMPLETE_TEMPLATE,
    "MYSTERY_BOX":     STAGE_MYSTERY_BOX_TEMPLATE,
}

# -------------------
# ITEM COORDINATES
# -------------------
START_BUTTON = (955, 650)
PLAY_BUTTON = (895, 620)
FAST_START_ITEM = (235, 600)
COOKIE_RELAY_ITEM = (385, 600)
RANDOM_BOOST_ITEM = (535, 600)
PURCHASE_BUTTON = (925, 295)
MULTI_PURCHASE_BUTTON = (1100, 195)
MULTI_BUY_BUTTON = (640, 587)
FAST_START_USE_BUTTON = (655, 340)
COOKIE_RELAY_USE_BUTTON = (655, 340)
COMPLETE_FINISH_BUTTON = (460, 625)
ACCEPT_MYSTERY_BOX_BUTTON = (650, 645)
ACCEPT_CONGRATULATIONS_BUTTON = (640, 565)
ACCEPT_LEVEL_UP_BUTTON = (640, 640)
ACCEPT_DAILY_CHECKIN_BUTTON = (640, 660)
ACCEPT_DAILY_TREASURE_BUTTON = (650, 570)
ACCEPT_ENTER_LEAGUE_BUTTON = (640, 460)
ACCEPT_LEAGUE_RESULTS_BUTTON = (640, 610)
ACCEPT_PREVIOUS_RANK_RESULTS_BUTTON = (640, 615)
RELIC_COMPLETE_BUTTON = (530, 110)
RELIC_CLAIM_BUTTON = (640, 580)
RELIC_CLOSE_BUTTON = (1076, 154)
CONNECTION_LOST_RELOAD_BUTTON = (640, 460)

# -------------------
# ANTI-BOT CAPTCHA
# -------------------
ANTI_BOT_CARD_POS_1 = (346, 179)
ANTI_BOT_CARD_POS_2 = (542, 179)
ANTI_BOT_CARD_POS_3 = (738, 179)
ANTI_BOT_CARD_POS_4 = (346, 435)
ANTI_BOT_CARD_POS_5 = (542, 435)
ANTI_BOT_CARD_POS_6 = (738, 435)
ANTI_BOT_CARD_WIDTH = 183
ANTI_BOT_CARD_HEIGHT = 241
